[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = '''
  Origin,
  Content-type'''


[[headers]]
  for = "/*/history.json"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = '''
  Origin,
  Content-type
  '''
  Cache-control = '''
  max-age: 5000
  '''
  X-Custom-Header = "foo"
