[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = "*"
  Access-Control-Expose-Headers = "*"
  Access-Control-Request-Headers = "*"
  Access-Control-Request-Method = "*"
  Cache-control = "public, max-age=0, must-revalidate"
