[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = '''
  Origin,
  Content-type'''
  Access-Control-Expose-Headers = "*"
  Access-Control-Request-Headers = "*"
