[[headers]]
  for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = '''
  Origin,
  Content-type'''
  for = "/marx/agora/history.json"
  [headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Headers = '''
  Origin,
  Content-type'''
  Cache-control = '''
   public,
   max-age=5000   
   '''
